[tools]
go = "1.26.1"
staticcheck = "2026.1"

[tasks.server]
description = "Run the cmd/server application in development mode"
run = "go run ./cmd/server.go"

[tasks.clean]
description = "Remove previous build artifaces"
run = "rm -rf ./bin"

[tasks.build]
description = "Build the server binary"
sources = ["go.sum", "go.mod", "**/*.go", "vendor/**/*"]
outputs = ["bin/subsonic-sanitizer"]
run = "go build -ldflags='-s' -o=./bin/subsonic-sanitizer ./cmd/server.go"

[tasks."build:linux:amd64"]
description = "Build the application binary application for linux/amd64"
env = { GOOS = 'linux', GOARCH = "amd64" }
run = { task = "build" }

[tasks.test]
description = "Runs tests"
run = "go test ./..."

[tasks.format]
description = "Format all .go files"
run = ["go fmt ./..."]

[tasks.tidy]
description = "Format all .go files and tidy module dependencies"
run = ["go mod tidy", "go mod verify", "go mod vendor", { task = "format" }]

[tasks.audit]
description = "Run quality control checks"
run = [
    "go mod tidy -diff",
    "go mod verify",
    "go vet ./...",
    "staticcheck ./...",
    "go test -race -vet=off ./...",
]
