[tools]
"aqua:goreleaser/goreleaser" = "latest"
go = "1.26.1"
staticcheck = "2026.1"

[tasks.server]
description = "Run the cmd/server application in development mode"
run = "go run ./cmd/server.go"

[tasks.clean]
description = "Remove previous build artifaces"
run = "rm -rf ./dist"

[tasks.build]
description = "Build the server binary"
run = "goreleaser build"

[tasks.release]
description = "Deploy a release"
run = "goreleaser release"

[tasks.test]
description = "Runs tests"
run = "go test ./..."

[tasks.format]
description = "Format all .go files"
run = ["go fmt ./..."]

[tasks.tidy]
description = "Format all .go files and tidy module dependencies"
run = ["go mod tidy", "go mod verify", "go mod vendor", { task = "format" }]

[tasks.audit]
description = "Run quality control checks"
run = [
    "go mod tidy -diff",
    "go mod verify",
    "go vet ./...",
    "staticcheck ./...",
    "go test -race -vet=off ./...",
]
